[bar]
order = [ "default" ]

[bar.default]
margin_ends = 0
background_opacity = 0.0
shadow = false
capsule = true
capsule_padding = 12
capsule_opacity = 0.95

start = [ "launcher", "workspaces", "media"]

end = [ "tray", "cpu", "temp", "ram", "notifications", "volume", "bluetooth", "network", "battery", "session" ]
