[shell]
polkit_agent = true

[shell.panel]
transparency_mode = "soft"
wallpaper_placement = "floating"
control_center_placement = "floating"
session_placement = "floating"
session_position = "center"
open_near_click_control_center = true

[shell.launcher]
categories = false
